import { useState } from 'react'
import { ClipboardCheck, Search, CalendarDays, RefreshCw, Plus } from 'lucide-react'
import { attendanceApi } from '../api/school'
import { apiError } from '../api/client'
import Modal from '../components/Modal'

const today = new Date().toISOString().slice(0,10)
export default function Attendance(){
 const [studentId,setStudentId]=useState(''),[items,setItems]=useState([]),[stats,setStats]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[dateFrom,setDateFrom]=useState(new Date(Date.now()-30*864e5).toISOString().slice(0,10)),[dateTo,setDateTo]=useState(today),[modal,setModal]=useState(false),[form,setForm]=useState({studentId:'',attendanceDate:today,status:'PRESENT',checkInTime:'',checkOutTime:'',remarks:''})
 async function load(){
  if(!studentId)return setError('Nhập Student ID trước.')
  setLoading(true);setError('')
  try{const [list,st]=await Promise.all([attendanceApi.student(studentId),attendanceApi.stats(studentId,dateFrom,dateTo)]);setItems(Array.isArray(list)?list:[]);setStats(st)}catch(e){setError(apiError(e))}finally{setLoading(false)}
 }
 async function mark(e){e.preventDefault();try{await attendanceApi.mark({...form,studentId:Number(form.studentId),attendanceDate:form.attendanceDate});setModal(false);if(String(form.studentId)===String(studentId))load()}catch(e){setError(apiError(e))}}
 return <><div className="page-head"><div><span className="eyebrow">ATTENDANCE</span><h1>Điểm danh</h1><p>Tra cứu lịch sử và ghi nhận điểm danh theo học sinh.</p></div><button className="primary-btn" onClick={()=>{setForm({...form,studentId:studentId||''});setModal(true)}}><Plus size={18}/> Ghi điểm danh</button></div>
 {error&&<div className="alert error">{error}</div>}
 <section className="panel filter-panel"><div className="filter-grid"><label><span>Student ID</span><div className="search-box"><Search size={17}/><input type="number" value={studentId} onChange={e=>setStudentId(e.target.value)} placeholder="Ví dụ: 1"/></div></label><label><span>Từ ngày</span><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></label><label><span>Đến ngày</span><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/></label><button className="secondary-btn align-end" onClick={load}><RefreshCw size={17}/> Tra cứu</button></div></section>
 <div className="stats-grid compact"><div className="stat-card"><div className="stat-icon blue"><ClipboardCheck size={20}/></div><div className="stat-copy"><span>Bản ghi</span><strong>{items.length}</strong></div></div><div className="stat-card"><div className="stat-icon green"><CalendarDays size={20}/></div><div className="stat-copy"><span>Thống kê</span><strong>{stats?.percentage ?? stats?.attendancePercentage ?? '—'}{stats && (stats?.percentage!=null||stats?.attendancePercentage!=null)?'%':''}</strong></div></div></div>
 <section className="panel"><div className="panel-head"><div><h2>Lịch sử điểm danh</h2><p>{studentId?`Student #${studentId}`:'Chưa chọn học sinh'}</p></div></div><div className="table-wrap"><table><thead><tr><th>Ngày</th><th>Học sinh</th><th>Trạng thái</th><th>Check in</th><th>Check out</th><th>Ghi chú</th></tr></thead><tbody>{loading?<tr><td colSpan="6"><div className="table-loading">Đang tải...</div></td></tr>:items.length===0?<tr><td colSpan="6"><div className="empty">Chưa có bản ghi.</div></td></tr>:items.map(a=><tr key={a.attendanceId}><td>{a.attendanceDate||'—'}</td><td>{a.studentName||a.studentId||'—'}</td><td><span className={`badge ${String(a.status||'').toLowerCase()}`}>{a.status||'—'}</span></td><td>{a.checkInTime||'—'}</td><td>{a.checkOutTime||'—'}</td><td>{a.remarks||'—'}</td></tr>)}</tbody></table></div></section>
 <Modal open={modal} onClose={()=>setModal(false)} title="Ghi nhận điểm danh"><form className="form-stack" onSubmit={mark}><Field label="Student ID" type="number" value={form.studentId} onChange={v=>setForm({...form,studentId:v})} required/><Field label="Ngày" type="date" value={form.attendanceDate} onChange={v=>setForm({...form,attendanceDate:v})} required/><label><span>Trạng thái</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['PRESENT','ABSENT','LATE','EXCUSED','HALF_DAY'].map(x=><option key={x}>{x}</option>)}</select></label><Field label="Check in" type="time" value={form.checkInTime} onChange={v=>setForm({...form,checkInTime:v})}/><Field label="Check out" type="time" value={form.checkOutTime} onChange={v=>setForm({...form,checkOutTime:v})}/><Field label="Ghi chú" value={form.remarks} onChange={v=>setForm({...form,remarks:v})}/><div className="modal-footer"><button type="button" className="secondary-btn" onClick={()=>setModal(false)}>Hủy</button><button className="primary-btn">Lưu</button></div></form></Modal>
 </>}
function Field({label,value,onChange,type='text',...rest}){return <label><span>{label}</span><input type={type} value={value??''} onChange={e=>onChange(e.target.value)} {...rest}/></label>}
