import { useEffect, useState } from 'react'
import { Plus, Pencil, Trash2, RefreshCw } from 'lucide-react'
import { examsApi } from '../api/school'
import { apiError } from '../api/client'
import Modal from '../components/Modal'

const blank={examName:'',description:'',subjectId:'',classId:'',examDate:'',startTime:'',endTime:'',durationMinutes:'',totalMarks:'100',passingMarks:'40',examType:'MIDTERM',status:'SCHEDULED',instructions:''}
export default function Exams(){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(blank),[saving,setSaving]=useState(false)
 async function load(){setLoading(true);setError('');try{const d=await examsApi.list();setItems(Array.isArray(d)?d:[])}catch(e){setError(apiError(e))}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 function edit(x){setEditing(x);setForm({...blank,...x,subjectId:x.subjectId??'',classId:x.classId??''});setModal(true)}
 async function save(e){e.preventDefault();setSaving(true);const p={...form,subjectId:Number(form.subjectId)||null,classId:Number(form.classId)||null,durationMinutes:Number(form.durationMinutes)||0,totalMarks:Number(form.totalMarks)||0,passingMarks:Number(form.passingMarks)||0};try{editing?await examsApi.update(editing.examId,p):await examsApi.create(p);setModal(false);await load()}catch(e){setError(apiError(e))}finally{setSaving(false)}}
 async function remove(id){if(!confirm('Xóa kỳ thi này?'))return;try{await examsApi.remove(id);await load()}catch(e){setError(apiError(e))}}
 return <><div className="page-head"><div><span className="eyebrow">EXAMINATION</span><h1>Kỳ thi</h1><p>Lập lịch, quản lý trạng thái và cấu hình bài thi.</p></div><div className="head-actions"><button className="secondary-btn" onClick={load}><RefreshCw size={17}/> Làm mới</button><button className="primary-btn" onClick={()=>{setEditing(null);setForm(blank);setModal(true)}}><Plus size={18}/> Tạo kỳ thi</button></div></div>
 {error&&<div className="alert error">{error}</div>}
 <section className="panel"><div className="table-wrap"><table><thead><tr><th>Kỳ thi</th><th>Môn / lớp</th><th>Ngày</th><th>Thời gian</th><th>Điểm</th><th>Trạng thái</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan="7"><div className="table-loading">Đang tải...</div></td></tr>:items.length===0?<tr><td colSpan="7"><div className="empty">Chưa có kỳ thi.</div></td></tr>:items.map(x=><tr key={x.examId}><td><strong>{x.examName}</strong><small>{x.examType||'—'}</small></td><td>{x.subjectName||x.subjectId||'—'}<small>{x.className||x.classId||'—'}</small></td><td>{x.examDate||'—'}</td><td>{x.startTime||'—'} {x.endTime?`→ ${x.endTime}`:''}</td><td>{x.totalMarks??'—'} / {x.passingMarks??'—'}</td><td><span className={`badge ${String(x.status||'').toLowerCase()}`}>{x.status||'—'}</span></td><td><div className="row-actions"><button className="icon-btn" onClick={()=>edit(x)}><Pencil size={16}/></button><button className="icon-btn danger" onClick={()=>remove(x.examId)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div></section>
 <Modal open={modal} onClose={()=>setModal(false)} title={editing?'Chỉnh sửa kỳ thi':'Tạo kỳ thi'} wide><form className="form-grid" onSubmit={save}>
 <Field label="Tên kỳ thi" value={form.examName} onChange={v=>setForm({...form,examName:v})} required wide/><Field label="Subject ID" type="number" value={form.subjectId} onChange={v=>setForm({...form,subjectId:v})}/><Field label="Class ID" type="number" value={form.classId} onChange={v=>setForm({...form,classId:v})}/><Field label="Ngày thi" type="date" value={form.examDate} onChange={v=>setForm({...form,examDate:v})}/><Field label="Bắt đầu" type="time" value={form.startTime} onChange={v=>setForm({...form,startTime:v})}/><Field label="Kết thúc" type="time" value={form.endTime} onChange={v=>setForm({...form,endTime:v})}/><Field label="Thời lượng (phút)" type="number" value={form.durationMinutes} onChange={v=>setForm({...form,durationMinutes:v})}/><Field label="Tổng điểm" type="number" value={form.totalMarks} onChange={v=>setForm({...form,totalMarks:v})}/><Field label="Điểm đạt" type="number" value={form.passingMarks} onChange={v=>setForm({...form,passingMarks:v})}/><label><span>Loại kỳ thi</span><select value={form.examType} onChange={e=>setForm({...form,examType:e.target.value})}>{['MIDTERM','FINAL','QUIZ','ASSIGNMENT','OTHER'].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Trạng thái</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{['SCHEDULED','ONGOING','COMPLETED','CANCELLED'].map(x=><option key={x}>{x}</option>)}</select></label><Field label="Hướng dẫn" value={form.instructions} onChange={v=>setForm({...form,instructions:v})} wide/><Field label="Mô tả" value={form.description} onChange={v=>setForm({...form,description:v})} wide/><div className="modal-footer"><button type="button" className="secondary-btn" onClick={()=>setModal(false)}>Hủy</button><button className="primary-btn" disabled={saving}>{saving?'Đang lưu...':'Lưu kỳ thi'}</button></div>
 </form></Modal></>
}
function Field({label,value,onChange,type='text',wide=false,...rest}){return <label className={wide?'field wide':''}><span>{label}</span><input type={type} value={value??''} onChange={e=>onChange(e.target.value)} {...rest}/></label>}
